[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@solidity-parser/=node_modules/solhint/node_modules/@solidity-parser/',
    'hardhat/=node_modules/hardhat/',
]
cache_path = 'forge-cache'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config